"""Training entry point, split from the former single ``train`` module."""

from __future__ import annotations

from dungeon_apprentice.training.callbacks import (
    CurriculumState,
    TierEvaluation,
    _activate_segment_seed,
    _CallbackFactory,
    _environment_factory,
    append_jsonl,
    atomic_copy_file,
    atomic_model_save,
    atomic_write_json,
    defaultdict,
    deque,
    ensure_disk_space,
    evaluate_policy,
    evaluation_seeds,
    make_curriculum_pixel_env,
    time,
    utc_now,
)
from dungeon_apprentice.training.cli import (
    DEFAULT_CURIOSITY_SCALE,
    EVALUATION_TIER_STRIDE,
    MINIMUM_GAMMA,
    Callable,
    _best_effort,
    _validate_args,
    build_parser,
    create_run_directory,
    git_snapshot,
    main,
    math,
    qualify,
    runtime_snapshot,
    start_dashboard,
    sys,
    traceback,
    uuid,
)

# The former single-file module also exposed everything it imported at top
# level, and callers read some of those names off the module. They are
# re-exported here from whichever split module still imports them, so the
# old surface stays intact.
from dungeon_apprentice.training.config import (
    CHECKPOINT_SCHEMA_VERSION,
    CURIOSITY_BUDGET,
    NEWEST_TIER_FRACTION,
    POLICY_KWARGS,
    PROMOTION_THRESHOLD,
    PROTOCOL,
    RETENTION_THRESHOLD,
    Any,
    DungeonTier,
    Image,
    Path,
    _actual_effective_config,
    _checkpoint_path,
    _config_differences,
    _CurriculumMastered,
    _json_scalar,
    _load_resume_metadata,
    _requested_effective_config,
    _require_training_packages,
    _safe_frame,
    _sidecar_path,
    annotations,
    argparse,
    file_sha256,
    json,
    np,
    os,
)

__all__ = [
    "CHECKPOINT_SCHEMA_VERSION",
    "CURIOSITY_BUDGET",
    "DEFAULT_CURIOSITY_SCALE",
    "EVALUATION_TIER_STRIDE",
    "MINIMUM_GAMMA",
    "NEWEST_TIER_FRACTION",
    "POLICY_KWARGS",
    "PROMOTION_THRESHOLD",
    "PROTOCOL",
    "RETENTION_THRESHOLD",
    "Any",
    "Callable",
    "CurriculumState",
    "DungeonTier",
    "Image",
    "Path",
    "TierEvaluation",
    "_CallbackFactory",
    "_CurriculumMastered",
    "_activate_segment_seed",
    "_actual_effective_config",
    "_best_effort",
    "_checkpoint_path",
    "_config_differences",
    "_environment_factory",
    "_json_scalar",
    "_load_resume_metadata",
    "_requested_effective_config",
    "_require_training_packages",
    "_safe_frame",
    "_sidecar_path",
    "_validate_args",
    "annotations",
    "append_jsonl",
    "argparse",
    "atomic_copy_file",
    "atomic_model_save",
    "atomic_write_json",
    "build_parser",
    "create_run_directory",
    "defaultdict",
    "deque",
    "ensure_disk_space",
    "evaluate_policy",
    "evaluation_seeds",
    "file_sha256",
    "git_snapshot",
    "json",
    "main",
    "make_curriculum_pixel_env",
    "math",
    "np",
    "os",
    "qualify",
    "runtime_snapshot",
    "start_dashboard",
    "sys",
    "time",
    "traceback",
    "utc_now",
    "uuid",
]
